using System.Text.Json.Serialization;
using HaPcRemote.Service.Models;
using HaPcRemote.Service.Services;

namespace HaPcRemote.Service;

[JsonSerializable(typeof(ApiResponse))]
[JsonSerializable(typeof(ApiResponse<HealthResponse>))]
[JsonSerializable(typeof(HealthResponse))]
[JsonSerializable(typeof(AppInfo))]
[JsonSerializable(typeof(ApiResponse<AppInfo>))]
[JsonSerializable(typeof(List<AppInfo>))]
[JsonSerializable(typeof(ApiResponse<List<AppInfo>>))]
[JsonSerializable(typeof(AudioDevice))]
[JsonSerializable(typeof(List<AudioDevice>))]
[JsonSerializable(typeof(ApiResponse<AudioDevice>))]
[JsonSerializable(typeof(ApiResponse<List<AudioDevice>>))]
[JsonSerializable(typeof(MonitorInfo))]
[JsonSerializable(typeof(List<MonitorInfo>))]
[JsonSerializable(typeof(ApiResponse<MonitorInfo>))]
[JsonSerializable(typeof(ApiResponse<List<MonitorInfo>>))]
[JsonSerializable(typeof(MacAddressInfo))]
[JsonSerializable(typeof(List<MacAddressInfo>))]
[JsonSerializable(typeof(SteamGame))]
[JsonSerializable(typeof(List<SteamGame>))]
[JsonSerializable(typeof(ApiResponse<List<SteamGame>>))]
[JsonSerializable(typeof(SteamRunningGame))]
[JsonSerializable(typeof(ApiResponse<SteamRunningGame>))]
[JsonSerializable(typeof(SteamBindings))]
[JsonSerializable(typeof(ApiResponse<SteamBindings>))]
[JsonSerializable(typeof(IReadOnlyList<string>))]
[JsonSerializable(typeof(ApiResponse<IReadOnlyList<string>>))]
[JsonSerializable(typeof(int))]
[JsonSerializable(typeof(ApiResponse<int>))]
[JsonSerializable(typeof(AudioState))]
[JsonSerializable(typeof(SystemState))]
[JsonSerializable(typeof(ApiResponse<SystemState>))]
[JsonSerializable(typeof(PowerConfig))]
[JsonSerializable(typeof(ApiResponse<PowerConfig>))]
[JsonSerializable(typeof(DisplayConfig))]
[JsonSerializable(typeof(ApiResponse<DisplayConfig>))]
[JsonSerializable(typeof(UpdateResult))]
[JsonSerializable(typeof(ApiResponse<UpdateResult>))]
[JsonSerializable(typeof(RunningGameDiagnostics))]
[JsonSerializable(typeof(ApiResponse<RunningGameDiagnostics>))]
[JsonSerializable(typeof(ShortcutDetectionTrace))]
[JsonSerializable(typeof(RunningProcess))]
[JsonSerializable(typeof(ArtworkDiagnostics))]
[JsonSerializable(typeof(ApiResponse<ArtworkDiagnostics>))]
[JsonSerializable(typeof(List<ArtworkDiagnostics>))]
[JsonSerializable(typeof(ApiResponse<List<ArtworkDiagnostics>>))]
[JsonSerializable(typeof(ArtworkPathCheck))]
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
public partial class AppJsonContext : JsonSerializerContext;
